language: python
python:
  - "3.3"
  - "pypy"

install:
  - "pip install -r requirements.txt"
  - "pip install MovieSerieTorrent"

script:
  - "python3 setup.py install"
  - "python3 tests/Rename_test.py"
